// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/20/2026, 3:06:03 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Administrator/Desktop/3/ecommerce-web/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/3/ecommerce-web/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/3/ecommerce-web/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/3/ecommerce-web/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/3/ecommerce-web/app/plugins/**/*.{js,ts,mjs}","C:/Users/Administrator/Desktop/3/ecommerce-web/app/composables/**/*.{js,ts,mjs}","C:/Users/Administrator/Desktop/3/ecommerce-web/app/utils/**/*.{js,ts,mjs}","C:/Users/Administrator/Desktop/3/ecommerce-web/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/3/ecommerce-web/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/3/ecommerce-web/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/3/ecommerce-web/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;