<template>
  <section class="page-pad fast-fade">
    <div class="mb-6"><h1 class="text-3xl font-black">إدارة العملاء</h1><p class="text-muted mt-2">سجل بيانات العميل، ارفع صور المستمسكات، أو التقط صورة مباشرة من كاميرا الهاتف.</p></div>
    <div v-if="message" class="mb-4 rounded-2xl border p-4 font-bold" :class="messageType==='error'?'border-red-500/40 text-red-500':'border-emerald-500/40 text-emerald-500'">{{message}}</div>
    <div class="card p-5 mb-6"><h2 class="mb-4 text-xl font-black">إضافة عميل</h2><div class="form-grid">
      <FormField label="اسم العميل الكامل" hint="الاسم الذي سيظهر في العقود والفواتير"><input v-model.trim="form.fullName" class="input" placeholder="اسم العميل"></FormField>
      <FormField label="رقم الهاتف الأساسي" hint="رقم التواصل الرئيسي"><input v-model.trim="form.phone" class="input" placeholder="رقم الهاتف"></FormField>
      <FormField label="رقم هاتف إضافي" hint="اختياري"><input v-model.trim="form.phone2" class="input" placeholder="هاتف إضافي"></FormField>
      <FormField label="عنوان العميل" hint="اختياري لكنه مفيد للأقساط والمتابعة"><input v-model.trim="form.address" class="input" placeholder="العنوان"></FormField>
      <FormField label="ملاحظات العميل" hint="أي ملاحظة خاصة بالتعامل أو المتابعة"><input v-model.trim="form.notes" class="input" placeholder="ملاحظات"></FormField>
      <FormField label="صور مستمسكات العميل" hint="يمكن اختيار صورة أو التقاطها من الهاتف مباشرة"><input class="input" type="file" accept="image/*" capture="environment" multiple @change="onFiles"></FormField>
      <div class="form-field justify-end"><span class="form-label">الإجراء</span><button class="btn-primary btn" :disabled="busy" @click="add">{{busy?'جاري الحفظ':'إضافة العميل'}}</button></div>
    </div><div v-if="formDocs.length" class="mt-4 grid gap-3 md:grid-cols-4"><img v-for="(img,i) in formDocs" :key="i" :src="img" class="h-32 w-full rounded-2xl object-cover border" style="border-color:var(--border)"></div></div>
    <div class="card overflow-x-auto"><table class="table"><thead><tr><th>الاسم</th><th>الهاتف</th><th>هاتف إضافي</th><th>العنوان</th><th>المستمسكات</th><th>إجراءات</th></tr></thead><tbody><tr v-for="c in customers" :key="c.id"><td class="font-black">{{c.fullName}}</td><td>{{c.phone}}</td><td>{{c.phone2 || '-'}}</td><td>{{c.address || '-'}}</td><td>{{Array.isArray(c.documentImages)?c.documentImages.length:0}}</td><td><div class="action-bar"><button class="btn-secondary btn py-2" @click="selectCustomer(c)">عرض/تعديل</button><button class="btn-danger btn py-2" @click="remove(c.id)">حذف</button></div></td></tr></tbody></table></div>
    <div v-if="selected" class="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4" @click.self="selected=null"><div class="card max-h-[90vh] w-full max-w-4xl overflow-auto p-6"><div class="mb-4 flex justify-between"><h3 class="text-2xl font-black">ملف العميل</h3><button class="btn-secondary btn" @click="selected=null">إغلاق</button></div><div class="grid gap-4 md:grid-cols-2"><FormField label="اسم العميل"><input v-model="selected.fullName" class="input"></FormField><FormField label="الهاتف"><input v-model="selected.phone" class="input"></FormField><FormField label="هاتف إضافي"><input v-model="selected.phone2" class="input"></FormField><FormField label="العنوان"><input v-model="selected.address" class="input"></FormField><FormField label="ملاحظات"><input v-model="selected.notes" class="input"></FormField><FormField label="إضافة مستمسك جديد" hint="صورة أو كاميرا الهاتف"><input class="input" type="file" accept="image/*" capture="environment" @change="onSelectedFile"></FormField></div><div class="mt-4 flex gap-2"><button class="btn-primary btn" @click="saveSelected">حفظ التعديل</button></div><div class="mt-5 grid gap-3 md:grid-cols-3"><img v-for="(img,i) in selectedDocs" :key="i" :src="img" class="h-44 w-full rounded-2xl object-cover border" style="border-color:var(--border)"></div></div></div>
  </section>
</template>
<script setup lang="ts">
const { data: customers, refresh } = useLazyFetch<any[]>('/api/customers', { default: () => [] })
const form=reactive({fullName:'',phone:'',phone2:'',address:'',notes:''}); const busy=ref(false); const formDocs=ref<string[]>([]); const selected=ref<any|null>(null); const selectedDocs=ref<string[]>([])
const message=ref(''); const messageType=ref<'ok'|'error'>('ok'); function notify(t:string,type:'ok'|'error'='ok'){message.value=t;messageType.value=type;setTimeout(()=>message.value='',3000)}
function fileToData(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader(); r.onload=()=>resolve(String(r.result)); r.onerror=reject; r.readAsDataURL(file)})}
async function onFiles(e:any){formDocs.value=[]; for(const f of Array.from(e.target.files||[]) as File[]) formDocs.value.push(await fileToData(f))}
async function add(){ if(!form.fullName||!form.phone) return notify('اكتب اسم العميل ورقم الهاتف','error'); busy.value=true; try{ await $fetch('/api/customers',{method:'POST',body:{...form,documentImages:formDocs.value}}); Object.assign(form,{fullName:'',phone:'',phone2:'',address:'',notes:''}); formDocs.value=[]; await refresh(); notify('تمت إضافة العميل') }catch(e:any){notify(e?.data?.message||'تعذر إضافة العميل','error')} finally{busy.value=false} }
function selectCustomer(c:any){ selected.value={...c}; selectedDocs.value=Array.isArray(c.documentImages)?[...c.documentImages]:[] }
async function onSelectedFile(e:any){ const f=e.target.files?.[0]; if(f) selectedDocs.value.push(await fileToData(f)) }
async function saveSelected(){ if(!selected.value) return; await $fetch(`/api/customers/${selected.value.id}`,{method:'PATCH',body:{fullName:selected.value.fullName,phone:selected.value.phone,phone2:selected.value.phone2,address:selected.value.address,notes:selected.value.notes,documentImages:selectedDocs.value}}); await refresh(); notify('تم حفظ بيانات العميل') }
async function remove(id:string){ if(confirm('هل تريد حذف العميل؟')){ await $fetch(`/api/customers/${id}`,{method:'DELETE'}); await refresh(); notify('تم حذف العميل') } }
</script>
