<template>
  <section class="page-pad fast-fade">
    <div class="mb-6"><h1 class="text-3xl font-black">الموظفون والصلاحيات</h1><p class="text-muted mt-2">حدد بدقة الصفحات التي يمكن لكل موظف الوصول إليها. موظف المبيعات لا يرى إلا الأقسام المسموحة له.</p></div>
    <div v-if="message" class="mb-4 rounded-2xl border p-4 font-bold" :class="messageType==='error'?'border-red-500/40 text-red-500':'border-emerald-500/40 text-emerald-500'">{{ message }}</div>
    <div class="card p-5 mb-6"><h2 class="mb-4 text-xl font-black">إضافة موظف جديد</h2><div class="form-grid">
      <FormField label="الاسم الكامل" hint="الاسم الذي سيظهر داخل النظام"><input v-model.trim="form.fullName" class="input" placeholder="مثال: أحمد محمد"></FormField>
      <FormField label="اسم الدخول" hint="اسم يستخدمه الموظف عند تسجيل الدخول"><input v-model.trim="form.username" class="input" placeholder="مثال: ahmed"></FormField>
      <FormField label="كلمة المرور" hint="لا تقل عن 4 أحرف"><input v-model="form.password" type="password" class="input" placeholder="كلمة مرور الموظف"></FormField>
      <FormField label="الدور العام" hint="الدور يعطي صلاحيات أولية ويمكن تخصيصها من القائمة"><select v-model="form.role" class="input"><option value="ADMIN">مدير كامل الصلاحيات</option><option value="ACCOUNTANT">محاسب</option><option value="SALES">موظف مبيعات</option><option value="VIEWER">مشاهدة فقط</option></select></FormField>
      <FormField label="صورة الموظف" hint="اختياري"><input class="input" type="file" accept="image/*" @change="onProfileImage"></FormField>
      <div class="form-field justify-end"><span class="form-label">الإجراء</span><button class="btn-primary btn" :disabled="busy" @click="add">{{ busy ? 'جاري الحفظ' : 'إضافة موظف' }}</button></div>
    </div><div class="mt-5"><h3 class="mb-3 font-black">صلاحيات الموظف الجديد</h3><div class="grid gap-2 md:grid-cols-3 lg:grid-cols-5"><label v-for="p in permissionOptions" :key="p.key" class="soft-card flex items-center gap-2 p-3"><input type="checkbox" v-model="form.permissions" :value="p.key"><span>{{p.label}}</span></label></div></div></div>
    <div class="card overflow-x-auto"><table class="table"><thead><tr><th>الموظف</th><th>اسم الدخول</th><th>الدور</th><th>الحالة</th><th>الصلاحيات</th><th>الإجراءات</th></tr></thead><tbody>
      <tr v-for="u in data" :key="u.id"><td class="font-black"><div class="flex items-center gap-3"><img v-if="u.profileImage" :src="u.profileImage" class="h-10 w-10 rounded-xl object-cover"><span>{{u.fullName}}</span></div></td><td>{{u.username}}</td><td><select v-model="u.role" class="input min-w-[160px]" :disabled="u.username==='admin'" @change="updateUser(u)"><option value="ADMIN">مدير</option><option value="ACCOUNTANT">محاسب</option><option value="SALES">مبيعات</option><option value="VIEWER">مشاهدة</option></select></td><td><span class="badge" :class="u.active?'text-emerald-500':'text-red-500'">{{u.active?'فعال':'معطل'}}</span></td><td><button class="btn-secondary btn py-2" @click="editPerms(u)">تعديل الصلاحيات</button></td><td><div class="action-bar"><button v-if="u.username!=='admin'" class="btn-secondary btn py-2" @click="toggleActive(u)">{{u.active?'تعطيل':'تفعيل'}}</button><button v-if="u.username!=='admin'" class="btn-danger btn py-2" @click="remove(u.id)">حذف</button><span v-else class="text-muted text-sm">حساب أساسي محمي</span></div></td></tr>
    </tbody></table></div>
    <div v-if="selected" class="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4" @click.self="selected=null"><div class="card w-full max-w-3xl p-6"><div class="mb-4 flex justify-between"><h3 class="text-2xl font-black">صلاحيات {{selected.fullName}}</h3><button class="btn-secondary btn" @click="selected=null">إغلاق</button></div><div class="grid gap-2 md:grid-cols-3"><label v-for="p in permissionOptions" :key="p.key" class="soft-card flex items-center gap-2 p-3"><input type="checkbox" v-model="selected.permissions" :value="p.key"><span>{{p.label}}</span></label></div><button class="btn-primary btn mt-5" @click="savePerms">حفظ الصلاحيات</button></div></div>
  </section>
</template>
<script setup lang="ts">
const { data, refresh } = useLazyFetch<any[]>('/api/employees', { default: () => [] })
const permissionOptions=[{key:'dashboard',label:'لوحة التحكم'},{key:'cars',label:'السيارات'},{key:'customers',label:'العملاء'},{key:'sales',label:'المبيعات'},{key:'installments',label:'الأقساط'},{key:'invoices',label:'الفواتير'},{key:'expenses',label:'المصاريف'},{key:'accounts',label:'الحسابات'},{key:'reports',label:'التقارير'},{key:'employees',label:'الموظفون'},{key:'settings',label:'الإعدادات'}]
const form=reactive<any>({fullName:'',username:'',password:'',role:'SALES',permissions:['dashboard','cars','customers','sales','installments','invoices'],profileImage:''})
const busy=ref(false); const message=ref(''); const messageType=ref<'ok'|'error'>('ok'); const selected=ref<any|null>(null)
function notify(text:string,type:'ok'|'error'='ok'){ message.value=text; messageType.value=type; setTimeout(()=>message.value='',3500) }
function onProfileImage(e:any){const f=e.target.files?.[0]; if(!f)return; const r=new FileReader(); r.onload=()=>form.profileImage=String(r.result); r.readAsDataURL(f)}
async function add(){ if(!form.fullName||!form.username||!form.password) return notify('أكمل بيانات الموظف أولاً','error'); busy.value=true; try{ await $fetch('/api/employees',{method:'POST',body:form}); Object.assign(form,{fullName:'',username:'',password:'',role:'SALES',permissions:['dashboard','cars','customers','sales','installments','invoices'],profileImage:''}); await refresh(); notify('تمت إضافة الموظف') }catch(e:any){ notify(e?.data?.message||'تعذر إضافة الموظف','error') }finally{busy.value=false} }
async function updateUser(u:any){ try{ await $fetch(`/api/employees/${u.id}`,{method:'PATCH',body:{role:u.role}}); notify('تم تحديث الدور') }catch(e:any){ notify(e?.data?.message||'تعذر تعديل الدور','error'); refresh() } }
function editPerms(u:any){ selected.value={...u, permissions:Array.isArray(u.permissions)?[...u.permissions]:[]} }
async function savePerms(){ await $fetch(`/api/employees/${selected.value.id}`,{method:'PATCH',body:{permissions:selected.value.permissions}}); selected.value=null; await refresh(); notify('تم حفظ الصلاحيات') }
async function toggleActive(u:any){ try{ await $fetch(`/api/employees/${u.id}`,{method:'PATCH',body:{active:!u.active}}); await refresh(); notify('تم تحديث حالة الحساب') }catch(e:any){ notify(e?.data?.message||'تعذر تعديل الحساب','error') } }
async function remove(id:string){ if(confirm('هل تريد حذف حساب الموظف؟ لا يمكن التراجع عن العملية.')){ try{ await $fetch(`/api/employees/${id}`,{method:'DELETE'}); await refresh(); notify('تم حذف الموظف') }catch(e:any){ notify(e?.data?.message||'تعذر حذف الموظف','error') } } }
</script>
