<template>
  <section class="page-pad fast-fade">
    <div class="mb-6 flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h1 class="text-3xl font-black">التقارير والإحصائيات</h1><p class="text-muted mt-2">ملخص حقيقي للمبيعات والأرباح والديون والمصروفات بدون تداخل في الأرقام.</p></div><button class="btn-primary btn" @click="refresh">تحديث التقارير</button></div>
    <div class="grid gap-4 lg:grid-cols-6 mb-6"><div class="card p-5 stat-card"><p class="text-muted">إجمالي المبيعات</p><b class="money-fit text-blue-500">{{compactMoney(data?.totalSalesIqd||0,'IQD')}}</b><div class="text-xs text-muted mt-2">{{money(data?.totalSalesIqd||0,'IQD')}}</div></div><div class="card p-5 stat-card"><p class="text-muted">صافي الربح</p><b class="money-fit text-emerald-500">{{compactMoney(data?.netProfitIqd||0,'IQD')}}</b><div class="text-xs text-muted mt-2">{{money(data?.netProfitIqd||0,'IQD')}}</div></div><div class="card p-5 stat-card"><p class="text-muted">الديون المتبقية</p><b class="money-fit text-amber-500">{{compactMoney(data?.debtIqd||0,'IQD')}}</b><div class="text-xs text-muted mt-2">{{money(data?.debtIqd||0,'IQD')}}</div></div><div class="card p-5 stat-card"><p class="text-muted">المصروفات</p><b class="money-fit text-red-500">{{compactMoney(data?.expenseIqd||0,'IQD')}}</b><div class="text-xs text-muted mt-2">{{money(data?.expenseIqd||0,'IQD')}}</div></div><div class="card p-5 stat-card"><p class="text-muted">إجمالي الشراء</p><b class="money-fit text-blue-500">{{compactMoney(data?.purchaseIqd||0,'IQD')}}</b><div class="text-xs text-muted mt-2">{{money(data?.purchaseIqd||0,'IQD')}}</div></div><div class="card p-5 stat-card"><p class="text-muted">ديون الشراء</p><b class="money-fit text-amber-500">{{compactMoney(data?.purchaseDebtIqd||0,'IQD')}}</b><div class="text-xs text-muted mt-2">{{money(data?.purchaseDebtIqd||0,'IQD')}}</div></div></div>
    <div class="card p-6"><h2 class="text-xl font-black mb-5">آخر العقود</h2><div class="overflow-x-auto"><table class="table"><thead><tr><th>العميل</th><th>السيارة</th><th>السعر</th><th>المدفوع</th><th>المتبقي</th><th>التاريخ</th></tr></thead><tbody><tr v-for="s in data?.latestSales" :key="s.id"><td>{{s.customer.fullName}}</td><td>{{s.car.brand}} {{s.car.model}}</td><td>{{money(s.salePrice,s.currency)}}</td><td>{{money(s.paidAmount,s.currency)}}</td><td>{{money(s.remainingAmount,s.currency)}}</td><td>{{dateText(s.saleDate)}}</td></tr><tr v-if="!data?.latestSales?.length"><td colspan="6" class="text-center text-muted py-8">لا توجد عقود بعد.</td></tr></tbody></table></div></div>

    <div class="card p-6 mt-6"><h2 class="text-xl font-black mb-5">آخر المشتريات</h2><div class="overflow-x-auto"><table class="table"><thead><tr><th>البائع</th><th>السيارة</th><th>قيمة الشراء</th><th>الواصل</th><th>الباقي</th><th>التاريخ</th></tr></thead><tbody><tr v-for="p in data?.latestPurchases" :key="p.id"><td>{{p.sellerName}}</td><td>{{p.carName}}</td><td>{{money(p.totalAmount,p.currency)}}</td><td>{{money(p.paidAmount,p.currency)}}</td><td>{{money(p.remainingAmount,p.currency)}}</td><td>{{dateText(p.fromDate)}}</td></tr><tr v-if="!data?.latestPurchases?.length"><td colspan="6" class="text-center text-muted py-8">لا توجد مشتريات بعد.</td></tr></tbody></table></div></div>
  </section>
</template>
<script setup lang="ts">const { data, refresh } = useLazyFetch<any>('/api/reports')</script>
